title: " "
description: PhD Student in Mathematics
url: https://saisanjeev.github.io
baseurl: ""

# Theme
remote_theme: mmistakes/minimal-mistakes@4.26.2
minimal_mistakes_skin: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Author
author:
  avatar: "assets/images/me.jpg"
  name: Sai Sanjeev Balakrishnan
  bio: PhD Student in Mathematics · University of California, Berkeley
  email: saisanjeev@berkeley.edu
  home: "/"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/saisanjeev2001"

# Navigation
navigation:
  main:
    - title: "About"
      url: /
    - title: "Publications"
      url: /publications/
    - title: "Teaching"
      url: /teaching/
    - title: "CV"
      url: /cv/
    - title: "Seminars"
      url: /seminars/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      classes: wide

# Reading files
include:
  - _pages

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  math_engine: mathjax
